//IF THE CLASS IS ABSTRACT, WE CAN'T INSTANTIATE ANY OBJECT ON THIS CLASS

public abstract class Machine {
	public abstract void start(); 
	//IMPLEMENTING ABSTRACT MEANS THESE METHODS SHOULD BE 
	//APPLIED FOR SURE IN CHILDREN CLASSES
	
	
	//SEE ABSTRACT CLASS VS INSTANCE 
}
